# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_age_appropriate',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_age_appropriate',
            field=models.IntegerField(default=0),
        ),
    ]
